// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CloudflareImage struct {
	ID         int64       `json:"id"`
	Path       []byte      `json:"path"`
	AuthorName pgtype.Text `json:"author_name"`
}
