// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CloudflareImage struct {
	ID        int64       `json:"id"`
	Path      pgtype.Text `json:"path"`
	ImageLink pgtype.Text `json:"image_link"`
}
