// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO Cloudflare_Image (path,image_link) VALUES ($1,$2)
`

type CreateImageParams struct {
	Path      pgtype.Text `json:"path"`
	ImageLink pgtype.Text `json:"image_link"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage, arg.Path, arg.ImageLink)
	return err
}
