// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	utils "github.com/tantanok221/cloudflare-image-backend/utils"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO Cloudflare_Image (path,author_name) VALUES ($1,$2)
`

type CreateImageParams struct {
	Path       utils.Path  `json:"path"`
	AuthorName pgtype.Text `json:"author_name"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage, arg.Path, arg.AuthorName)
	return err
}
